document.write("<p><a href='/ITU-D/ict/publications/' class='navleft'>Publications</a></p>");
document.write("<p><a href='/ITU-D/ict/statistics/' class='navleft'>Free Statistics</a></p>");
document.write("<p><a href='/ITU-D/ict/cs/' class='navleft'>Internet Case<br>Studies</a></p>");
document.write("<p><a href='/ITU-D/ict/papers/' class='navleft'>Presentations</a></p>");
document.write("<p><a href='/ITU-D/ict/links/' class='navleft'>Industry Sites<br> and Links</a></p>");
document.write("<p><a href='/ITU-D/ict/conferences/' class='navleft'>Conferences</a></p>");
document.write("<p>&nbsp;</p>");
