postgres: &postgres
  adapter: postgresql
  encoding: unicode
  port: <%= ENV.fetch("POSTGRES_PORT_5432_TCP_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *postgres
  database: grid_arendal_dev

test: &test
  <<: *postgres
  database: grid_arendal_test

production:
  <<: *postgres
  database: grid_arendal_pro

cucumber:
  <<: *test
